export const FETCH_POKEMON_REQUEST = "FETCH_POKEMON_REQUEST";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_ERROR = "FETCH_POKEMON_ERROR";
export const SET_POKEMON_ERROR = "SET_POKEMON_ERROR";
export const CLEAR_POKEMON_DATA = "CLEAR_POKEMON_DATA";
